version: "3.7"
services:

  # nginx service
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - custom

  # application service
  app:
    container_name: "app"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/application
    image: app
    environment:
      - ASYNC_SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8000"
    networks:
      - custom
    depends_on:
      - db

  # database service
  db:
      image: postgres:14-alpine
      restart: always
      environment:
        - POSTGRES_DB=test_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./postgres_data/db:/var/lib/postgresql/data/
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - custom

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@example.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    ports:
      - "5050:80"
    depends_on:
      - db


networks:
  custom:
    driver: bridge